In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

# 1. DataFrame : The stuctured data which is made up of rows and columns like Table

In [3]:

               # Create Dataframe

df = pd.DataFrame([1,2,3],columns = ["Col_name"])
print(df)

   Col_name
0         1
1         2
2         3

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
data = {
        "Name" :  ["Nikhil","Omkar","Krish","Sai"],
        "Age" : [21,22,23,24],
        "Monthly_Salary" : [30000,40000,50000,54000]
}

In [6]:
df = pd.DataFrame(data)
print(df)

     Name  Age  Monthly_Salary
0  Nikhil   21           30000
1   Omkar   22           40000
2   Krish   23           50000
3     Sai   24           54000

In [7]:
type(df)

pandas.core.frame.DataFrame

# 2. Basic DataFrame Understanding

In [8]:

df.head(2)

     Name  Age  Monthly_Salary
0  Nikhil   21           30000
1   Omkar   22           40000

In [9]:
df.tail(2)

    Name  Age  Monthly_Salary
2  Krish   23           50000
3    Sai   24           54000

In [10]:
df.shape

(4, 3)

In [11]:
df.columns     # show the all column

Index(['Name', 'Age', 'Monthly_Salary'], dtype='object')

In [12]:
df.rename(columns = {"Salary": "Monthly_Salary"})

     Name  Age  Monthly_Salary
0  Nikhil   21           30000
1   Omkar   22           40000
2   Krish   23           50000
3     Sai   24           54000

In [13]:
df

     Name  Age  Monthly_Salary
0  Nikhil   21           30000
1   Omkar   22           40000
2   Krish   23           50000
3     Sai   24           54000

In [14]:
df.rename(columns = {"Salary": "Monthly_Salary"},inplace=True)        # inplace
df

     Name  Age  Monthly_Salary
0  Nikhil   21           30000
1   Omkar   22           40000
2   Krish   23           50000
3     Sai   24           54000

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      object
 1   Age             4 non-null      int64
 2   Monthly_Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [16]:
df.describe()      # it shows statistical summary

             Age  Monthly_Salary
count   4.000000         4.00000
mean   22.500000     43500.00000
std     1.290994     10754.84387
min    21.000000     30000.00000
25%    21.750000     37500.00000
50%    22.500000     45000.00000
75%    23.250000     51000.00000
max    24.000000     54000.00000

# 3. save and load data

In [17]:
df.to_csv('Test_data.csv', index=False)

In [18]:
load_df = pd.read_csv('Test_data.csv')
load_df

     Name  Age  Monthly_Salary
0  Nikhil   21           30000
1   Omkar   22           40000
2   Krish   23           50000
3     Sai   24           54000

# 4. Rows and Columns

In [19]:
# Select Column
# df[["Name"]]  single column

df[["Name"]]

     Name
0  Nikhil
1   Omkar
2   Krish
3     Sai

In [20]:
df[["Name","Monthly_Salary"]]

     Name  Monthly_Salary
0  Nikhil           30000
1   Omkar           40000
2   Krish           50000
3     Sai           54000

In [21]:
# Select Rows

In [22]:
# loc[] is used for label based indexing

In [23]:
df.loc[df.Name=="Nikhil"]        # loc is index name based

     Name  Age  Monthly_Salary
0  Nikhil   21           30000

In [24]:
df.loc[(df.Name=="Nikhil")&(df.Monthly_Salary>=25000)]

     Name  Age  Monthly_Salary
0  Nikhil   21           30000

In [25]:
# Rows Selection

In [26]:
# iloc : index value based

In [27]:
df.iloc[0]

Name              Nikhil
Age                   21
Monthly_Salary     30000
Name: 0, dtype: object

In [28]:
df.iloc[0:2]           # [start:stop:step]

     Name  Age  Monthly_Salary
0  Nikhil   21           30000
1   Omkar   22           40000

In [29]:
df.loc[0:2]

     Name  Age  Monthly_Salary
0  Nikhil   21           30000
1   Omkar   22           40000
2   Krish   23           50000

# 5. Filter DataFrame

In [30]:
# it is used to filter the rows and columns data we can filter by > or < using

In [31]:
df

     Name  Age  Monthly_Salary
0  Nikhil   21           30000
1   Omkar   22           40000
2   Krish   23           50000
3     Sai   24           54000

In [32]:
df['Age'] > 22

0    False
1    False
2     True
3     True
Name: Age, dtype: bool

In [33]:
df[df["Age"] > 22]               # > is used for only greater than

    Name  Age  Monthly_Salary
2  Krish   23           50000
3    Sai   24           54000

In [34]:
df[df["Age"] >= 22]              # >= is used for greater than and equqls to

    Name  Age  Monthly_Salary
1  Omkar   22           40000
2  Krish   23           50000
3    Sai   24           54000

In [35]:
df[(df["Age"] >= 22) & (df["Monthly_Salary"] >= 40000)]       # in this & is used for took more than 1 columns we can take more than 1 column

    Name  Age  Monthly_Salary
1  Omkar   22           40000
2  Krish   23           50000
3    Sai   24           54000

In [36]:

df.where(df["Age"] >= 23)

# where is used for showing null values to specific rows and columns

    Name   Age  Monthly_Salary
0    NaN   NaN             NaN
1    NaN   NaN             NaN
2  Krish  23.0         50000.0
3    Sai  24.0         54000.0

In [37]:
df.where(df["Age"] >= 23, other = "Not Eligible")

           Name           Age Monthly_Salary
0  Not Eligible  Not Eligible   Not Eligible
1  Not Eligible  Not Eligible   Not Eligible
2         Krish            23          50000
3           Sai            24          54000

# 6. Rows and Columns - Operation (Add,Update,Delete)

In [38]:
# add new column

df["Team"]= ["CEO","HR","CTO","DA"]                   # added a new column Team
df

     Name  Age  Monthly_Salary Team
0  Nikhil   21           30000  CEO
1   Omkar   22           40000   HR
2   Krish   23           50000  CTO
3     Sai   24           54000   DA

In [39]:
df["Bonus"]= df["Monthly_Salary"]*0.2
df

     Name  Age  Monthly_Salary Team    Bonus
0  Nikhil   21           30000  CEO   6000.0
1   Omkar   22           40000   HR   8000.0
2   Krish   23           50000  CTO  10000.0
3     Sai   24           54000   DA  10800.0

In [40]:
# add new rows

df.loc[len(df)]=['ABC',25,21000,'IT',2000]
df

     Name  Age  Monthly_Salary Team    Bonus
0  Nikhil   21           30000  CEO   6000.0
1   Omkar   22           40000   HR   8000.0
2   Krish   23           50000  CTO  10000.0
3     Sai   24           54000   DA  10800.0
4     ABC   25           21000   IT   2000.0

In [41]:
len(df)

5

In [42]:
# Update value - Using index value

df.loc[0,"Monthly_Salary"]=35000
df

     Name  Age  Monthly_Salary Team    Bonus
0  Nikhil   21           35000  CEO   6000.0
1   Omkar   22           40000   HR   8000.0
2   Krish   23           50000  CTO  10000.0
3     Sai   24           54000   DA  10800.0
4     ABC   25           21000   IT   2000.0

In [43]:
# Updating value - Using Column Value

df.loc[df.Name=="Nikhil","Monthly_Salary"]=30000
df

     Name  Age  Monthly_Salary Team    Bonus
0  Nikhil   21           30000  CEO   6000.0
1   Omkar   22           40000   HR   8000.0
2   Krish   23           50000  CTO  10000.0
3     Sai   24           54000   DA  10800.0
4     ABC   25           21000   IT   2000.0

In [44]:
# Delete value - row and column values

df.drop(df[df.Name=="ABC"].index)

     Name  Age  Monthly_Salary Team    Bonus
0  Nikhil   21           30000  CEO   6000.0
1   Omkar   22           40000   HR   8000.0
2   Krish   23           50000  CTO  10000.0
3     Sai   24           54000   DA  10800.0

In [45]:
df[df.Name=="ABC"]

  Name  Age  Monthly_Salary Team   Bonus
4  ABC   25           21000   IT  2000.0

In [46]:
df.drop("Bonus",axis=1)

     Name  Age  Monthly_Salary Team
0  Nikhil   21           30000  CEO
1   Omkar   22           40000   HR
2   Krish   23           50000  CTO
3     Sai   24           54000   DA
4     ABC   25           21000   IT

In [47]:
df.drop(["Bonus","Team"],axis=1)

     Name  Age  Monthly_Salary
0  Nikhil   21           30000
1   Omkar   22           40000
2   Krish   23           50000
3     Sai   24           54000
4     ABC   25           21000

In [48]:
df.drop(1,axis=0,inplace=True)

In [49]:
df.drop(df[df.Name=="ABC"].index)          # drop row, axis = 0
df.drop("Bonus",axis=1,inplace=True)       # drop column
df

     Name  Age  Monthly_Salary Team
0  Nikhil   21           30000  CEO
2   Krish   23           50000  CTO
3     Sai   24           54000   DA
4     ABC   25           21000   IT

In [50]:
df

     Name  Age  Monthly_Salary Team
0  Nikhil   21           30000  CEO
2   Krish   23           50000  CTO
3     Sai   24           54000   DA
4     ABC   25           21000   IT

In [51]:
df.sort_values("Monthly_Salary")             # Ascending to Descending order

     Name  Age  Monthly_Salary Team
4     ABC   25           21000   IT
0  Nikhil   21           30000  CEO
2   Krish   23           50000  CTO
3     Sai   24           54000   DA

In [52]:
df.sort_values("Monthly_Salary",ascending = False)     # descending to ascending order

     Name  Age  Monthly_Salary Team
3     Sai   24           54000   DA
2   Krish   23           50000  CTO
0  Nikhil   21           30000  CEO
4     ABC   25           21000   IT

# 7. Working with Date and Value

In [53]:
df.drop(df[df.Name=="ABC"].index)

     Name  Age  Monthly_Salary Team
0  Nikhil   21           30000  CEO
2   Krish   23           50000  CTO
3     Sai   24           54000   DA

In [54]:
df

     Name  Age  Monthly_Salary Team
0  Nikhil   21           30000  CEO
2   Krish   23           50000  CTO
3     Sai   24           54000   DA
4     ABC   25           21000   IT

In [55]:
df["DOJ"] = ["2024-01-01", "2024-01-15", "2024-03-28", "2024-03-03"]
df

     Name  Age  Monthly_Salary Team         DOJ
0  Nikhil   21           30000  CEO  2024-01-01
2   Krish   23           50000  CTO  2024-01-15
3     Sai   24           54000   DA  2024-03-28
4     ABC   25           21000   IT  2024-03-03

In [56]:
df["DOJ"].dtype

dtype('O')

In [57]:
df["Doj"] = pd.to_datetime(df["DOJ"])

In [58]:
df["DOJ"].dtype

dtype('O')

In [59]:
df1 = df

In [60]:
df1["DOJ2"] = ["01-01-2025","15-01-2025","28-03-2025","03-03-2025"]       # Upadated values
df1

     Name  Age  Monthly_Salary Team         DOJ        Doj        DOJ2
0  Nikhil   21           30000  CEO  2024-01-01 2024-01-01  01-01-2025
2   Krish   23           50000  CTO  2024-01-15 2024-01-15  15-01-2025
3     Sai   24           54000   DA  2024-03-28 2024-03-28  28-03-2025
4     ABC   25           21000   IT  2024-03-03 2024-03-03  03-03-2025

In [61]:
df1["DOJ2"].dtype

dtype('O')

In [62]:
df1["DOJ2"] = pd.to_datetime(df1["DOJ2"],format="%d-%m-%Y")         # Format is used to change the format
df1

     Name  Age  Monthly_Salary Team         DOJ        Doj       DOJ2
0  Nikhil   21           30000  CEO  2024-01-01 2024-01-01 2025-01-01
2   Krish   23           50000  CTO  2024-01-15 2024-01-15 2025-01-15
3     Sai   24           54000   DA  2024-03-28 2024-03-28 2025-03-28
4     ABC   25           21000   IT  2024-03-03 2024-03-03 2025-03-03

In [63]:
df1["DOJ2"].dtype

dtype('<M8[ns]')

In [64]:
df = df.drop("DOJ2",axis=1)          # delete the last column

In [65]:
df

     Name  Age  Monthly_Salary Team         DOJ        Doj
0  Nikhil   21           30000  CEO  2024-01-01 2024-01-01
2   Krish   23           50000  CTO  2024-01-15 2024-01-15
3     Sai   24           54000   DA  2024-03-28 2024-03-28
4     ABC   25           21000   IT  2024-03-03 2024-03-03

# Extract year, month, week, day

In [66]:
df["DOJ"] = pd.to_datetime(df["DOJ"], format="%Y-%m-%d")
df

     Name  Age  Monthly_Salary Team        DOJ        Doj
0  Nikhil   21           30000  CEO 2024-01-01 2024-01-01
2   Krish   23           50000  CTO 2024-01-15 2024-01-15
3     Sai   24           54000   DA 2024-03-28 2024-03-28
4     ABC   25           21000   IT 2024-03-03 2024-03-03

In [67]:
df["DOJ"].dt.year

0    2024
2    2024
3    2024
4    2024
Name: DOJ, dtype: int32

In [68]:
df["DOJ"].dt.month

0    1
2    1
3    3
4    3
Name: DOJ, dtype: int32

In [69]:
df["DOJ"].dt.day_name()

0      Monday
2      Monday
3    Thursday
4      Sunday
Name: DOJ, dtype: object

In [70]:
df["Month"] = df["DOJ"].dt.month      # we can store month in it

In [71]:
df

     Name  Age  Monthly_Salary Team        DOJ        Doj  Month
0  Nikhil   21           30000  CEO 2024-01-01 2024-01-01      1
2   Krish   23           50000  CTO 2024-01-15 2024-01-15      1
3     Sai   24           54000   DA 2024-03-28 2024-03-28      3
4     ABC   25           21000   IT 2024-03-03 2024-03-03      3

In [72]:
df["DOJ"]+pd.Timedelta(days=90)      # Timedelta, we can add no of days, years in it
                                        # Difference between two dates and times

0   2024-03-31
2   2024-04-14
3   2024-06-26
4   2024-06-01
Name: DOJ, dtype: datetime64[ns]

# 8. Handelling Missing Values

In [73]:
df

     Name  Age  Monthly_Salary Team        DOJ        Doj  Month
0  Nikhil   21           30000  CEO 2024-01-01 2024-01-01      1
2   Krish   23           50000  CTO 2024-01-15 2024-01-15      1
3     Sai   24           54000   DA 2024-03-28 2024-03-28      3
4     ABC   25           21000   IT 2024-03-03 2024-03-03      3

In [74]:
df.isnull()

    Name    Age  Monthly_Salary   Team    DOJ    Doj  Month
0  False  False           False  False  False  False  False
2  False  False           False  False  False  False  False
3  False  False           False  False  False  False  False
4  False  False           False  False  False  False  False

In [75]:
import numpy as np
df.loc[df.Name == "ABC","Monthly_Salary"] = np.nan
df

     Name  Age  Monthly_Salary Team        DOJ        Doj  Month
0  Nikhil   21         30000.0  CEO 2024-01-01 2024-01-01      1
2   Krish   23         50000.0  CTO 2024-01-15 2024-01-15      1
3     Sai   24         54000.0   DA 2024-03-28 2024-03-28      3
4     ABC   25             NaN   IT 2024-03-03 2024-03-03      3

In [76]:
df.isnull()

    Name    Age  Monthly_Salary   Team    DOJ    Doj  Month
0  False  False           False  False  False  False  False
2  False  False           False  False  False  False  False
3  False  False           False  False  False  False  False
4  False  False            True  False  False  False  False

In [77]:
df.isnull().sum()         # if there are so many data and we have to get only null values then use sum()

Name              0
Age               0
Monthly_Salary    1
Team              0
DOJ               0
Doj               0
Month             0
dtype: int64

In [78]:
df.fillna(0)

     Name  Age  Monthly_Salary Team        DOJ        Doj  Month
0  Nikhil   21         30000.0  CEO 2024-01-01 2024-01-01      1
2   Krish   23         50000.0  CTO 2024-01-15 2024-01-15      1
3     Sai   24         54000.0   DA 2024-03-28 2024-03-28      3
4     ABC   25             0.0   IT 2024-03-03 2024-03-03      3

# 9. Aggregation and groupby

In [79]:
df["Team"].value_counts()

Team
CEO    1
CTO    1
DA     1
IT     1
Name: count, dtype: int64

In [80]:
df["Month"].value_counts()

Month
1    2
3    2
Name: count, dtype: int64

In [81]:
df[df["Month"]==1].value_counts()     # only if we have to take specify values
                                      # value_counts gives frequency of values

Name    Age  Monthly_Salary  Team  DOJ         Doj         Month
Krish   23   50000.0         CTO   2024-01-15  2024-01-15  1        1
Nikhil  21   30000.0         CEO   2024-01-01  2024-01-01  1        1
Name: count, dtype: int64

In [84]:
# Aggregation based on groupby

df.groupby("Month")["Monthly_Salary"].sum()       # sum() uses when sum of given month salary

Month
1    80000.0
3    54000.0
Name: Monthly_Salary, dtype: float64

In [85]:
df.groupby("Month")["Monthly_Salary"].mean()      # mean() uses when avg Salary have

Month
1    40000.0
3    54000.0
Name: Monthly_Salary, dtype: float64

In [86]:
df.groupby("Month").agg({"Monthly_Salary": "mean", "Name":"count"})        # agg stands for aggregation

       Monthly_Salary  Name
Month
1             40000.0     2
3             54000.0     2

# 10. Concatenate and Merge Dataframes (Joins)

In [87]:
df1 = pd.DataFrame({"ID":[1,2,3],"Name":["A","B","C"]})

In [88]:
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [90]:
df2 = pd.DataFrame({"ID":[1,2,3,4],"Score":[88,96,77,79]})

In [91]:
df2

   ID  Score
0   1     88
1   2     96
2   3     77
3   4     79

In [92]:
pd.concat([df1, df2],axis = 0)        # vertical / row level / top on top

   ID  Score
0   1     88
1   2     96
2   3     77
3   4     79
0   1     88
1   2     96
2   3     77
3   4     79

In [93]:
pd.concat([df1, df2],axis = 1)          # Horizontal / column level / side on side

   ID  Score  ID  Score
0   1     88   1     88
1   2     96   2     96
2   3     77   3     77
3   4     79   4     79

# Merge = Join

In [94]:
pd.merge(df1,df2, how = "inner", on = "ID")

   ID  Score_x  Score_y
0   1       88       88
1   2       96       96
2   3       77       77
3   4       79       79

In [95]:
pd.merge(df1,df2, how = "left", on = "ID")

   ID  Score_x  Score_y
0   1       88       88
1   2       96       96
2   3       77       77
3   4       79       79

In [96]:
pd.merge(df1,df2, how = "right", on = "ID")

   ID  Score_x  Score_y
0   1       88       88
1   2       96       96
2   3       77       77
3   4       79       79

In [97]:
pd.merge(df1,df2, how = "outer", on = "ID")

   ID  Score_x  Score_y
0   1       88       88
1   2       96       96
2   3       77       77
3   4       79       79

In [98]:
pd.merge(df1, df2, how = "inner", left_on = "ID", right_on = "ID")

   ID  Score_x  Score_y
0   1       88       88
1   2       96       96
2   3       77       77
3   4       79       79

# 11. AI and ChatGPT

In [99]:
df

     Name  Age  Monthly_Salary Team        DOJ        Doj  Month
0  Nikhil   21         30000.0  CEO 2024-01-01 2024-01-01      1
2   Krish   23         50000.0  CTO 2024-01-15 2024-01-15      1
3     Sai   24         54000.0   DA 2024-03-28 2024-03-28      3
4     ABC   25             NaN   IT 2024-03-03 2024-03-03      3

In [103]:
df[(df["Month"]==1) & (df["Monthly_Salary"] >= 30000)]

     Name  Age  Monthly_Salary Team        DOJ        Doj  Month
0  Nikhil   21         30000.0  CEO 2024-01-01 2024-01-01      1
2   Krish   23         50000.0  CTO 2024-01-15 2024-01-15      1