In [ ]:
DataFrame

In [20]:
import pandas as pd
dicts = {"Name" :["Nikhil","Nagnath","Mundkar","Omkar","Krish","Amol"],
        "Age":[21,44,55,33,44,21],
         "City": ["Nanded","Tkali","Mumbai","Pune","Jaur","HYD"]
        }
df=pd.DataFrame(dicts)
df

      Name  Age    City
0   Nikhil   21  Nanded
1  Nagnath   44   Tkali
2  Mundkar   55  Mumbai
3    Omkar   33    Pune
4    Krish   44    Jaur
5     Amol   21     HYD

In [9]:
# method 2 = read_CSV : load the dataset

pd.read_csv("C:\\Users\\Nikhil\\Downloads\\dataset.csv")

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [13]:
# two types

pd.read_csv("C:\\Users\\Nikhil\\Downloads\\dataset.csv")
df1 = pd.read_csv("C:/Users/Nikhil/Downloads/dataset.csv")

In [ ]:
# method 3 : head() : display top five methods
# method 4 : tail() : display last five methods
# method 5 : sample() : display random rows
# method 6 : shape() : check the size of dataset
# method 7 : info() : check the information about the dataset
# method 8 : columns() : check the column names of the datasets
# method 9 : dtypes() : check the all columns of data
# method 10 : isnull() : check the missing value  /
# method 11 : isna() : check the missing value
# method 12 : select the single column  []
# method 13 : select the multiple columns with [[]]
# method 14 : select_dtype : select the specific type of column
# method 15 : describe : show the statsitical summary of 
# method 16 : drop() : drop the columns
# method 17 : duplicated() : check the duplicated rows
# method 18 : value_count()
# method 19 : rename() : change the column name
# method 20 : astype() : change the type of column name
# method 21 : filna() : fill the missing values

# method 30 : to_numeric()
# method 31 : apply()
# method 32 : iloc() 
# method 33 : loc()

In [15]:
df.sample

<bound method NDFrame.sample of       Name  Age
0   Nikhil   21
1  Nagnath   44
2  Mundkar   55
3    Omkar   33
4    Krish   44
5     Amol   21>

In [6]:
df.info

<bound method DataFrame.info of       Name  Age
0   Nikhil   21
1  Nagnath   44
2  Mundkar   55>

In [16]:
df.head

<bound method NDFrame.head of       Name  Age
0   Nikhil   21
1  Nagnath   44
2  Mundkar   55
3    Omkar   33
4    Krish   44
5     Amol   21>

In [20]:
type(df)

pandas.core.frame.DataFrame

In [21]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [23]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [27]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [29]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [31]:
# single column
Target=df['target']

In [34]:
df[['target','sex','cp']]

     target  sex  cp
0         1    1   3
1         1    1   2
2         1    0   1
3         1    1   1
4         1    0   0
..      ...  ...  ..
298       0    0   0
299       0    1   3
300       0    1   0
301       0    1   0
302       0    0   1

[303 rows x 3 columns]

In [40]:
int_columns = df.select_dtypes(include = ["int64"]).columns
int_columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [41]:
df.select_dtypes(include = ["float"]).columns

Index(['oldpeak'], dtype='object')

In [43]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [ ]:
df.drop("exang"),axis = 1,inplace = True

In [52]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [53]:
df.duplicated().sum()

np.int64(1)

In [56]:
df.drop_duplicates(inplace = True)

In [57]:
df.duplicated().sum()

np.int64(0)

In [58]:
df["target"].value_counts()

target
1    164
0    138
Name: count, dtype: int64

In [59]:
df["target"].value_counts(dropna = True)

target
1    164
0    138
Name: count, dtype: int64

In [35]:
# rename() : change the column name

#df.rename(columns = {"target": "Result", "sex": "Gender"}, inplace = True)
#print(df.columns)

In [13]:
df.rename(index = {0: "first",1,"second"})

SyntaxError: ':' expected after dictionary key (519504402.py, line 1)

In [14]:
df.columns = [col.title() for col in df.columns]

In [15]:
df=df.add_prefix("col_")

In [16]:
df.head()

  col_Name  col_Age
0   Nikhil       21
1  Nagnath       44
2  Mundkar       55

In [26]:
df['Col_oldpeak']=df['Col_oldpeak'].astype("int")
df.['col_Oldpeak']

SyntaxError: invalid syntax (1801775143.py, line 2)

In [24]:
df.['col_oldpeak']

SyntaxError: invalid syntax (3726200198.py, line 1)

In [29]:
# DataFrame

df = pd.DataFrame(dicts)
df.

      Name  Age
0   Nikhil   21
1  Nagnath   44
2  Mundkar   55

In [30]:
df.isnull().sum()

Name    0
Age     0
dtype: int64

In [31]:
df['Age'].value_counts(dropna = False)

Age
21    1
44    1
55    1
Name: count, dtype: int64

In [41]:
df['Age'].fillna('unknow',inplace = True)
df

C:\Users\Nikhil\AppData\Local\Temp\ipykernel_16172\3690972765.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna('unknow',inplace = True)

      Name  Age
0   Nikhil   21
1  Nagnath   44
2  Mundkar   55

# Mean

In [42]:
age_mean = int(df['Age'].mean())
age_mean

40

In [43]:
df['Age'] = df['Age'].fillna(age_mean)

In [44]:
df['Age']= df['Age'].astype("int")
df['Age']

0    21
1    44
2    55
Name: Age, dtype: int64

In [52]:
age_median = df['Age'].median()
age_median

44.0

In [2]:
# Date columns handelling
import pandas as pd
df = pd.DataFrame({'date': ['2024-01-15', '2024-02-20', '20204-03-25']})
df

          date
0   2024-01-15
1   2024-02-20
2  20204-03-25

In [ ]:
# apply()
df["CreditScore"].apply(lambda x )

In [18]:
# method 32 : iloc() [start : stop]

df.iloc[0:5]

      Name  Age
0   Nikhil   21
1  Nagnath   44
2  Mundkar   55
3    Omkar   33
4    Krish   44

In [19]:
# method : loc[]

df.loc[0:5]

      Name  Age
0   Nikhil   21
1  Nagnath   44
2  Mundkar   55
3    Omkar   33
4    Krish   44
5     Amol   21

In [21]:
df.iloc[0:5,1:3]

   Age    City
0   21  Nanded
1   44   Tkali
2   55  Mumbai
3   33    Pune
4   44    Jaur

In [24]:
df.loc[1:5,["Name","Age"]]

      Name  Age
1  Nagnath   44
2  Mundkar   55
3    Omkar   33
4    Krish   44
5     Amol   21

In [ ]:
df.loc["row_labe","column_label"]                                               # Syntax of loc
df.iloc[Start_row_index: Stop_row_index, Start_col_index: Stop_col_index]       # Syntax of iloc

In [28]:
df.iloc[:,-1]

0    Nanded
1     Tkali
2    Mumbai
3      Pune
4      Jaur
5       HYD
Name: City, dtype: object